USE datamart_kbb;

DROP TABLE IF EXISTS dim_product_scd1;
CREATE TABLE `dim_product_scd1` (
  `PRODUCT_KEY` BIGINT(20) NOT NULL DEFAULT '-1',
  `PROD_CODE` VARCHAR(11) NOT NULL DEFAULT '-',
  `PRODUCT_DESC` VARCHAR(256) NOT NULL DEFAULT '-',
  `UNIT_PRICE` DOUBLE DEFAULT '0',
  `CATEGORY` VARCHAR(256) NOT NULL DEFAULT '-',
  `VERSION` BIGINT(20) DEFAULT NULL,
  `DATE_FROM` DATETIME DEFAULT NULL,
  `DATE_TO` DATETIME DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_KEY`),
  KEY `IX_BUS_KEY` (`PROD_CODE`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS dim_product_scd2;
CREATE TABLE `dim_product_scd2` (
  `product_key` BIGINT(20) NOT NULL DEFAULT '-1',
  `prod_code` VARCHAR(11) NOT NULL DEFAULT '-',
  `product_desc` VARCHAR(256) DEFAULT '-',
  `unit_price` DOUBLE DEFAULT '0',
  `category` VARCHAR(256) DEFAULT '-',
  `version` BIGINT(20) DEFAULT NULL,
  `date_from` DATETIME DEFAULT NULL,
  `date_to` DATETIME DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

USE target_db;

DROP TABLE IF EXISTS stg_prod_catalog;
CREATE TABLE `stg_prod_catalog` (
  `prod_code` VARCHAR(11) DEFAULT NULL,
  `prod_desc` VARCHAR(256) DEFAULT NULL,
  `price` DOUBLE DEFAULT NULL,
  `category` VARCHAR(256) DEFAULT NULL
) ENGINE=MYISAM DEFAULT CHARSET=utf8
;